# Question 1

Create a null vector of size 10 but the fifth value which is 1 

In [10]:
# Import the numpy package under the name np
import numpy as np

# you answer here

vector = np.zeros(10)
vector[4] = 1

print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Question 2

Create a 10x10 array with random values and find the  maximum values

In [11]:
# Import the numpy package under the name np
import numpy as np

# you answer here


arr = np.random.rand(10, 10)
max_value = np.amax(arr)

print(arr)
print("Maximum Value:", max_value)

[[0.03792198 0.81759825 0.39223678 0.22872413 0.38040209 0.70139485
  0.32945647 0.92363588 0.76164738 0.15269223]
 [0.10657218 0.42271869 0.24202474 0.48905514 0.04739267 0.49598887
  0.0027556  0.93904437 0.5352733  0.42973311]
 [0.48489502 0.94638735 0.90685256 0.85539113 0.40609472 0.48406652
  0.9885009  0.33260757 0.30805513 0.76273045]
 [0.63008636 0.17204866 0.49964245 0.18456014 0.83115597 0.74243081
  0.55681166 0.23278122 0.6655072  0.68424535]
 [0.92841935 0.94044792 0.19806796 0.17417758 0.94708531 0.76497938
  0.68623644 0.7128853  0.7811074  0.96037942]
 [0.6532893  0.34345507 0.38952382 0.67634254 0.90450764 0.66395567
  0.42454156 0.56527731 0.25860646 0.14639816]
 [0.89613228 0.93150427 0.55575527 0.23924092 0.15803457 0.74467468
  0.15062425 0.37988021 0.45526818 0.42364342]
 [0.83865877 0.64267783 0.28473201 0.22774505 0.5377928  0.77207659
  0.9483041  0.5802514  0.05127379 0.21854286]
 [0.78914953 0.85155869 0.26513944 0.04334058 0.82177774 0.93210195
  0.91418546

# Question 3

How to add a border (filled with 0's) around the following existing array? The end results should be a matrix of 7 x 7 matrix with all 0's along the four boarders. 



In [13]:
import numpy as np

existing_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

new_array = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)

print("Existing Array:")
print(existing_array)
print("Array with Border:")
print(new_array)

Existing Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Array with Border:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]
